export const PARTICIPANTS_FETCHED = 'wcwagers.PARTICIPANTS_FETCHED';
export const SET_CONTRACT_ADDRESS = 'wcwagers.SET_CONTRACT_ADDRESS';
export const SHOW_CONTEST_DETAILS_DIALOG = 'wcwagers.SHOW_CONTEST_DETAILS_DIALOG';

export const CONTEST_DETAILS = 'wcwagers.CONTEST_DETAILS';
export const PARTICIPANT_REGISTRATION_TX_STATUS = 'wcwagers.PARTICIPANT_REGISTRATION_TX_STATUS';
export const BETS_TX_STATUS = 'wcwagers.BETS_TX_STATUS';

export const PHASES_DATES_FETCHED = 'wcwagers.PHASES_DATES_FETCHED';


export const BETS_SUBMITTED_FETCHED = 'wcwagers.BETS_SUBMITTED_FETCHED';
export const OTHER_PARTICIPANTS_BETS_FETCHED = 'wcwagers.OTHER_PARTICIPANTS_BETS_FETCHED';

export const SHOW_MATCH_PREDICTIONS_DIALOG = 'wcwagers.SHOW_MATCH_PREDICTIONS_DIALOG';


