export const PARTICIPANTS_FETCHED = 'wcwagers.PARTICIPANTS_FETCHED';
export const SET_CONTRACT_ADDRESS = 'wcwagers.SET_CONTRACT_ADDRESS';
export const SHOW_CONTEST_DETAILS_DIALOG = 'wcwagers.SHOW_CONTEST_DETAILS_DIALOG';

export const CONTEST_DETAILS = 'wcwagers.CONTEST_DETAILS';


